name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Build project
        run: nix develop --command bash -c "cmake -B build && cmake --build build"
      - name: Format check
        run: nix develop --command bash -c "./scripts/format.sh && git diff --exit-code"
      - name: Static analysis check
        run: nix develop --command bash -c "./scripts/check.sh --error-exitcode=2"
