name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build statically linked binary
        run: |
          nix develop --command cmake -B build -DSTATIC_BUILD=ON
          nix develop --command cmake --build build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/rpg-raylib
